import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { data } from '../../data';
import './Portfolio.css';
import EducationChart from '../Education/EducationChart';

const Arrow = () => <span aria-hidden="true">↗</span>;
export function PortfolioNav() {
  const [open, setOpen] = useState(false);
  const location = useLocation();
  useEffect(() => { setOpen(false); if (location.hash) requestAnimationFrame(() => document.getElementById(location.hash.slice(1))?.scrollIntoView()); }, [location]);
  return <header className="portfolio-nav"><Link className="wordmark" to="/" aria-label="Mohammed Abdullah home">ma<span>®</span></Link><button className="menu-toggle" aria-expanded={open} aria-controls="main-navigation" onClick={() => setOpen(!open)}>{open ? 'Close −' : 'Menu +'}</button><nav id="main-navigation" className={open ? 'is-open' : ''} aria-label="Main navigation">{[['projects','Selected work'],['work','Experience'],['about','About']].map(([id,label]) => <Link key={id} to={`/#${id}`} onClick={() => setOpen(false)}>{label}</Link>)}<a className="nav-contact" href={`mailto:${data.information.email}`}>Let’s talk <Arrow /></a></nav></header>;
}
function SystemGraphic() {
  return <div className="system-graphic" role="img" aria-label="Animated illustration of data flowing through an AI system to deployed intelligence"><div className="graphic-caption"><span>SYSTEM / INTELLIGENCE</span><span className="status-dot">IN MOTION</span></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="system-core"><div className="core-cross">✳</div><span>AI</span></div><div className="system-node node-input"><small>01 / INPUT</small><strong>Raw data</strong><div className="signal-bars">{[18,30,22,38,16,28,34,20,30].map((h,i)=><i key={i} style={{height:h,animationDelay:`${i*.15}s`}}/>)}</div></div><div className="system-node node-model"><small>02 / PROCESS</small><strong>Intelligence</strong><span className="node-code">learn → reason → act</span></div><div className="system-node node-output"><small>03 / DEPLOY</small><strong>Real-world impact <span>↗</span></strong><div className="output-line"/></div><div className="graphic-bottom"><span>FROM RESEARCH TO REALITY</span><span>● ● ●</span></div></div>;
}
const clean = value => String(value || '').replace(/<[^>]*>/g,' ').trim();
export default function Portfolio() {
 const [filter,setFilter] = useState('All');
 const types = ['All',...new Set(data.projects.map(p=>p.type))];
 return <main className="portfolio"><section id="home" className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span className="tiny-square"/> MOHAMMED ABDULLAH · AI ENGINEER</p><h1>Intelligence.<br/>Engineered for<br/><span>the real world.</span></h1><p className="hero-description">I turn complex data into systems that see, reason, and act. From the first experiment to production at scale.</p><div className="hero-actions"><a className="button button-lime" href="#projects">Explore my work <Arrow/></a><a className="text-link" href="#resume">View résumé <span aria-hidden="true">↓</span></a></div><p className="hero-location">BASED IN CHENNAI, INDIA <span>12.98° N / 80.27° E</span></p></div><SystemGraphic/></section><div className="expertise-strip"><div className="wrap"><span>BUILT AT THE INTERSECTION OF</span><strong>AI & machine learning</strong><i>✳</i><strong>Distributed systems</strong><i>✳</i><strong>Computer vision</strong></div></div>
 <section className="metrics wrap" aria-label="Career highlights">{data.information.highlights.map(h=><div key={h.value}><strong>{h.value}</strong><p>{h.label}</p></div>)}</section>
 <section id="projects" className="projects-section wrap"><div className="section-top"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Less theory.<br/><span>More possibility.</span></h2></div><p>Explorations, experiments, and systems.<br/>A few things I’ve brought to life.</p></div><div className="project-filters" aria-label="Filter projects">{types.map(t=><button key={t} aria-pressed={filter===t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t}{t==='All' && <span>{data.projects.length}</span>}</button>)}</div><div className="project-grid">{data.projects.map((p,i)=>({...p,index:i})).filter(p=>filter==='All'||p.type===filter).map(p=><Link to={`/projectpage/${p.index}`} key={p.index} className="project-card"><div className={`project-art art-${p.index%4}`}>{p.thumbnail ? <img src={p.thumbnail} alt={`${p.title} preview`} loading="lazy"/> : <div className="abstract-art" aria-hidden="true"><span>{['⌘','◉','⌁','✳'][p.index%4]}</span><small>{p.type}</small></div>}<span className="project-open"><Arrow/></span></div><div className="project-meta"><span>{p.type}</span><span>{String(p.index+1).padStart(2,'0')}</span></div><h3>{p.title}</h3><p>{clean(p.description).split('\n')[0].slice(0,150)}</p></Link>)}</div></section>
 <section id="work" className="experience-section"><div className="wrap"><div className="section-top"><div><p className="eyebrow">02 / EXPERIENCE</p><h2>Built with purpose.<br/><span>Backed by practice.</span></h2></div><span className="section-symbol" aria-hidden="true">↳</span></div>{data.work.map((w,i)=><Link to={`/workpage/${i}`} className="experience-row" key={i}><span className="experience-date">{w.dates}</span><div><h3>{w.title}</h3><span>{w.company}</span><p>{clean(w.description)}</p></div><Arrow/></Link>)}</div></section>
 <section id="about" className="about-section wrap"><div><p className="eyebrow">03 / THE PERSON BEHIND THE SYSTEMS</p><h2>Curiosity is<br/>the <span>constant.</span></h2><p className="about-intro">I’m Mohammed Abdullah.<br/>Engineer by practice. Explorer by instinct.</p><p>{data.information.description}</p><div className="social-links">{data.information.profiles.map(p=><a href={p.url} key={p.media} target="_blank" rel="noreferrer">{p.media} <Arrow/></a>)}</div></div><div id="skills" className="skill-panel"><p className="eyebrow">MY TOOLKIT</p>{data.skills.map(s=><details key={s.type}><summary>{s.type}<span>+</span></summary>{Object.entries(s).filter(([k])=>k!=='type').map(([k,v])=><p key={k}><strong>{k}</strong><br/>{v}</p>)}</details>)}</div></section>
 <section className="credentials wrap"><div id="education"><p className="eyebrow">04 / FOUNDATIONS</p><h2>Always learning.</h2><EducationChart/>{data.education.map((e,i)=><div className="education-row" key={i}><span>{e['Year of Passing']}</span><div><h3>{e.Institution}</h3><p>{e.Type}</p><strong>{e.Grade}</strong></div></div>)}</div><div id="achievements"><p className="eyebrow">RECOGNITION</p>{data.achievements.map((a,i)=><p className="achievement" key={i}><span>↗</span>{a}</p>)}<details id="certifications" className="certificate-list"><summary>Certifications <span>{data.certifications.length} +</span></summary>{data.certifications.map((c,i)=><Link key={i} to={`/certificatepage/${i}`}>{c.title}<Arrow/></Link>)}</details></div></section>
 <section id="resume" className="resume-section wrap"><div className="section-top"><div><p className="eyebrow">05 / RÉSUMÉ</p><h2>The full picture.</h2></div><div className="resume-actions"><a className="text-link" href={data.resume.file} target="_blank" rel="noreferrer">Open full screen <Arrow/></a><a className="button button-lime" href={data.resume.file} download={data.resume.fileName}>Download PDF ?</a></div></div><p className="resume-note">Read my résumé here. Updated {data.resume.updated}. If the preview is unavailable on your device, use Open full screen.</p><iframe className="resume-viewer" src={`${data.resume.file}#view=FitH`} title="Mohammed Abdullah résumé" loading="lazy"/></section><section id="contact" className="contact-section"><div className="wrap"><p className="eyebrow">HAVE SOMETHING IN MIND?</p><a className="contact-headline" href={`mailto:${data.information.email}`}>Let’s build<br/>what’s next.<Arrow/></a><div className="contact-bottom"><a href={`mailto:${data.information.email}`}>{data.information.email}</a><a href="#resume">Download résumé ↓</a></div></div></section><footer className="portfolio-footer wrap"><Link className="wordmark" to="/">ma<span>®</span></Link><span>© {new Date().getFullYear()} Mohammed Abdullah</span><Link to="/privacy">Privacy</Link><a href="#home">Back to top ↑</a></footer>
 </main>;
}
